export const TEST_ACTION = 'TEST_ACTION';
export const LOGIN_USER_USERNAME = 'LOGIN_USER_USERNAME';
export const CHANGE_VIDEO_FILE = 'CHANGE_VIDEO_FILE';
export const CHANGE_EDIT_VIDEO_INFO = 'CHANGE_EDIT_VIDEO_INFO';
export const SET_USER_CHANNEL = 'SET_USER_CHANNEL';
export const SET_ACCOUNT_INFO = 'SET_ACCOUNT_INFO';
export const SET_USER_AVATAR = 'SET_USER_AVATAR';
export const ACCOUNT_NOT_FOUND = 'ACCOUNT_NOT_FOUND';
